mysqlLocal:
  type: com.alibaba.druid.pool.DruidDataSource
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/maanshan?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
  username: root
  password: 123456

mysqlRemote:
  type: com.alibaba.druid.pool.DruidDataSource
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/maanshan?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
  username: root
  password: 123456


