  spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.178.133.153:3306/minorfish-version-manager?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: minorfish

# ===============================
# = JWT
# ===============================
  token:
    debug: true
    header: X-Auth-Token
    secret: project-manager@minor.com
    expiration: 99997200  # Token expiration time in seconds


 # ===============================
 # = 文件上传
 # ===============================
  upload:
    path: /opt/upload/
    baseUrl: http://clinic-weichat.minorfish.com:91/